### ISSUE TITLE
INFOGRAFIA- HERNANDEZ MATRA JORGE LUIS

### ISSUE THREAD

**Issue by JORGELUIS2266** [SistemasTecTlaxiaco/actividad-4-infografia-de-libreria-JORGELUIS2266#1]
[Infografía de LIBRERIA.pdf](https://github.com/SistemasTecTlaxiaco/actividad-4-infografia-de-libreria-JORGELUIS2266/files/14657353/Infografia.de.LIBRERIA.pdf)

**Comment by SandyMarissaGs** [comment]
De acuerdo a la rúbrica obtuviste el 19%

**Comment by josealfredo79** [comment]
bien hecho y revisado...
